package restAssuredTests;

import static org.hamcrest.CoreMatchers.equalTo;

import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import io.qameta.allure.Description;
import io.qameta.allure.Epic;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import io.qameta.allure.Story;
import io.restassured.RestAssured;
import net.bytebuddy.NamingStrategy.SuffixingRandom.BaseNameResolver.ForGivenType;
import static io.restassured.RestAssured.*;
import io.restassured.parsing.Parser;
import io.restassured.response.Response;

import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.CoreMatchers.containsString;
import static org.hamcrest.Matcher.*;
import java.util.LinkedHashMap.*;

public class Retail_Connectors_Demo 
{
	@BeforeMethod
	public void configBeforeMethod()
	{
		RestAssured.baseURI="https://eportuat.equifax.co.in/cir360Report/cir360Report";
		RestAssured.registerParser("text/plain", Parser.JSON);
	}
	@Test
	public void PCS_ERS_EE_EIS_Test()

	{
		//RestAssured.baseURI="https://eportuat.equifax.co.in/cir360Report/cir360Report";
		//RestAssured.registerParser("text/plain", Parser.JSON);
		String palload="{\r\n"
				+ "    \"RequestHeader\": {\r\n"
				+ "        \"CustomerId\": \"21\",\r\n"
				+ "        \"UserId\": \"kavithav\",\r\n"
				+ "		\"Password\": \"Bigil@123\",\r\n"
				+ "        \"MemberNumber\": \"027BB02400\",\r\n"
				+ "        \"SecurityCode\": \"N42\",\r\n"
				+ "        \"ProductCode\": [\"PCS\"],\r\n"
				+ "        \"CustRefField\": \"REF16271\"\r\n"
				+ "    },\r\n"
				+ "    \"RequestBody\": {\r\n"
				+ "        \"InquiryPurpose\": \"16\",\r\n"
				+ "        \"TransactionAmount\": \"100\",\r\n"
				+ "        \"FirstName\": \"VIJAY  SINGH    MEHTA\",\r\n"
				+ "        \"MiddleName\": \"\",\r\n"
				+ "        \"LastName\": \"\",\r\n"
				+ "        \"InquiryAddresses\": [\r\n"
				+ "            {\r\n"
				+ "                \"seq\": \"1\",\r\n"
				+ "                \"AddressType\": [\r\n"
				+ "                    \"H\"\r\n"
				+ "                ],\r\n"
				+ "                \"AddressLine1\": \"199/1 GANDHI GRAM NEW BASTI NEW PARK  ROAD MB 7217217222 DEHRADUN\",\r\n"
				+ "                \"AddressLine2\": \"\",\r\n"
				+ "                \"Locality\": \"\",\r\n"
				+ "                \"City\": \"\",\r\n"
				+ "                \"State\": \"UL\",\r\n"
				+ "                \"Postal\": \"248001\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"InquiryPhones\": [\r\n"
				+ "            {\r\n"
				+ "                \"seq\": \"1\",\r\n"
				+ "                \"Number\": \"7830645084\",\r\n"
				+ "                \"PhoneType\": [\r\n"
				+ "                    \"M\"\r\n"
				+ "                ]\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"EmailAddresses\": [],\r\n"
				+ "        \"IDDetails\": [\r\n"
				+ "            {\r\n"
				+ "                \"seq\": \"1\",\r\n"
				+ "                \"IDType\": \"T\",\r\n"
				+ "                \"IDValue\": \"CIBPM5563R\",\r\n"
				+ "                \"Source\": \"Inquiry\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"DOB\": \"1988-06-05\"\r\n"
				+ "    },\r\n"
				+ "    \"Score\": [\r\n"
				+ "       {\r\n"
				+ "            \"Type\": \"EE\",\r\n"
				+ "            \"Version\": \"3.0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"Type\": \"EIS\",\r\n"
				+ "            \"Version\": \"3.0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"Type\": \"ERS\",\r\n"
				+ "            \"Version\": \"3.0\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"InternalConfig\": {\r\n"
				+ "        \"configDetails\": {\r\n"
				+ "            \"SOURCE\": \"XML\"\r\n"
				+ "        }\r\n"
				+ "    }\r\n"
				+ "}";
		given()
			.contentType("application/json")
			.body(palload)
		.when()
			.post()
		.then()
			.statusCode(200)
			.body("InquiryRequestInfo.InquiryPurpose", equalTo("16"))
			.body("InquiryRequestInfo.TransactionAmount", equalTo("100"))
			.body("InquiryRequestInfo.FirstName", is("VIJAY  SINGH    MEHTA"))
			.body("InquiryResponseHeader.SuccessCode", equalTo("1"))
			.body("CCRResponse.Status", is("1"));
			
			
			
			
		//.extract()
			//.response().toString();
			//String info=from(response).getList("");
		
			//.body("CCRResponse", hasSize(1));
			//.body("", greather(20));
		    //body("store.book.author*.length().sum()", greaterThan(50)).
			//.body("InquiryRequestInfo", equalTo("7"))
			//.body("store.book.author.collect { it.length() }.sum()", greaterThan(50));
			//.body("InquiryRequestInfo.cllect{it.length()}.sum()", equalTo(7));
			
			//.body("InquiryRequestInfo.InquiryAddresses", containsString("Postal=248001"))
			//.body("InquiryRequestInfo.InquiryAddresses.AddressLine1", containsString("<[199/1 GANDHI GRAM NEW BASTI NEW PARK  ROAD MB 7217217222 DEHRADUN]>"))
			//.log().all();
			
	}
     
	@Test
	public void Webthick_Test()
	{
		String Webthick_Payload="{\r\n"
				+ "    \"RequestHeader\": {\r\n"
				+ "        \"CustomerId\": \"21\",\r\n"
				+ "        \"UserId\": \"sxb578\",\r\n"
				+ "        \"Password\": \"abcd@1234\",\r\n"
				+ "        \"MemberNumber\": \"007FZ00016\",\r\n"
				+ "        \"SecurityCode\": \"YT9\",\r\n"
				+ "        \"ProductCode\": [\r\n"
				+ "            \"ESR02\"\r\n"
				+ "        ],\r\n"
				+ "        \"CustRefField\": \"REF16271\",\r\n"
				+ "        \"ReportOrderNo\": \"538492\"\r\n"
				+ "    },\r\n"
				+ "    \"RequestBody\": {\r\n"
				+ "        \"InquiryPurpose\": \"05\",\r\n"
				+ "        \"TransactionAmount\": \"100\",\r\n"
				+ "        \"FirstName\": \"NITISH\",\r\n"
				+ "        \"LastName\": \"KUMAR\",\r\n"
				+ "        \"InquiryAddresses\": [\r\n"
				+ "            {\r\n"
				+ "                \"seq\": \"1\",\r\n"
				+ "                \"AddressLine1\": \"Flat no -004 tower A-6\",\r\n"
				+ "                \"AddressLine2\": \"Saviour greenisle crossing\",\r\n"
				+ "                \"State\": \"UP\",\r\n"
				+ "                \"Postal\": \"201016\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"InquiryPhones\": [\r\n"
				+ "            {\r\n"
				+ "                \"seq\": \"1\",\r\n"
				+ "                \"Number\": \"9431046500\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"IDDetails\": [\r\n"
				+ "            {\r\n"
				+ "                \"seq\": \"1\",\r\n"
				+ "                \"IDType\": \"T\",\r\n"
				+ "                \"IDValue\": \"CJRPK4585N\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"DOB\": \"1993-11-12\",\r\n"
				+ "        \"Gender\": \"M\",\r\n"
				+ "        \"CustomFields\": [\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"DEDUPE_FLAG\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"COMP_LOAN_FLAG\",\r\n"
				+ "                \"value\": \"NA\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_UNIQUE_CATEGORIES_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"CASINO_GAMING_APPS_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TRAVEL_APPS_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NUM_APPROVALS_OFF_PINCODE_CAT\",\r\n"
				+ "                \"value\": \"1326\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"RESIDENCE_TYPE\",\r\n"
				+ "                \"value\": \"With Parents\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"EDUCATION\",\r\n"
				+ "                \"value\": \"Graduate degree\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NO_TIMES_SUSPENDED\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_SMSES_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NO_CALLS_KNWLTY_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SECS_25_50\",\r\n"
				+ "                \"value\": \"194\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"ES_CLICKS\",\r\n"
				+ "                \"value\": \"11\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"APP_CLICKS_CAT\",\r\n"
				+ "                \"value\": \"11\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SAL_45_DAY\",\r\n"
				+ "                \"value\": \"V\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SALARY_NOT_IDENTIFIED\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NUM_BOUNCES_PERF\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"BOUNCES\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"DECLARATION_BUCKET\",\r\n"
				+ "                \"value\": \"B_High\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"IMPS_FLAG\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"ALCOHOL_PERF_CAT\",\r\n"
				+ "                \"value\": \"1\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"CREDIT_CARD_PAYMENT_PERF_CAT\",\r\n"
				+ "                \"value\": \"5\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"INSURANCE_PERF_CAT\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NUM_CASH_DEPOSITS_PERF\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"PERFIOS_BOUNCES3M_TOTAL_BOUNCES_CAT\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"AVERAGE_DAILY_BALANCE_CAT\",\r\n"
				+ "                \"value\": \"2520\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SALARY\",\r\n"
				+ "                \"value\": \"41896.0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"FB_FRIEND_DEFAULT\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"USER_ID\",\r\n"
				+ "                \"value\": \"176\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"REPORT_ORDER_NUMBER\",\r\n"
				+ "                \"value\": \"537406\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"FB_CONNECTIONS_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_INCOMING_DURATION_SECS_CAT\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SOURCE_TYPE\",\r\n"
				+ "                \"value\": \"WEB\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"DPD_30\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"INCOMING_OVERALL_CALL_RATIO\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"AVGCALLSPERDAY_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"AGE\",\r\n"
				+ "                \"value\": \"29\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"INCOMING_DURATION_HRS_CALL_HIST_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"CORP_FLAG\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"JOURNEY_REJECT_FRNDS_PHBK_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"OVERDUE_SMSES_COUNT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"FB_CONN_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"CHANNEL\",\r\n"
				+ "                \"value\": \"WEB\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"WORKFLOW_ID\",\r\n"
				+ "                \"value\": \"4\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SMALL_CITY\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_DURATION_SECS_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_CONTACTS_PHBK_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"EXPERIENCE_MONTHS_CAT\",\r\n"
				+ "                \"value\": \"86\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"FILE_TYPE\",\r\n"
				+ "                \"value\": \"THICK\"\r\n"
				+ "            }\r\n"
				+ "        ]\r\n"
				+ "    }\r\n"
				+ "}";
		given()
			.contentType("application/json")
			.body(Webthick_Payload)
		.when()
			.post()
		.then()
			.assertThat().statusCode(200)
			.body("InquiryResponseHeader.SuccessCode", equalTo("0"));
			//.log().all();
					
	}
	
	
	
	@Test()
	@Description("This Test Case is APP_NTC_Test")
	@Epic("Retail")
	@Story("Retail Story")
	@Severity(SeverityLevel.CRITICAL)
	
	public void APP_NTC_Test()
	{
		String APP_NTC_PayLoad="{\r\n"
				+ "    \"RequestHeader\": {\r\n"
				+ "        \"CustomerId\": \"21\",\r\n"
				+ "        \"UserId\": \"\",\r\n"
				+ "        \"Password\": \"\",\r\n"
				+ "        \"MemberNumber\": \"007FZ00016\",\r\n"
				+ "        \"SecurityCode\": \"YT9\",\r\n"
				+ "        \"ProductCode\": [\r\n"
				+ "            \"ESR02\"\r\n"
				+ "        ],\r\n"
				+ "        \"CustRefField\": \"REF16271\",\r\n"
				+ "        \"ReportOrderNo\": \"828785\"\r\n"
				+ "    },\r\n"
				+ "    \"RequestBody\": {\r\n"
				+ "        \"InquiryPurpose\": \"05\",\r\n"
				+ "        \"TransactionAmount\": \"100\",\r\n"
				+ "        \"FirstName\": \"NITISH\",\r\n"
				+ "        \"LastName\": \"KUMAR\",\r\n"
				+ "        \"InquiryAddresses\": [\r\n"
				+ "            {\r\n"
				+ "                \"seq\": \"1\",\r\n"
				+ "                \"AddressLine1\": \"Flat no -004 tower A-6\",\r\n"
				+ "                \"AddressLine2\": \"Saviour greenisle crossing\",\r\n"
				+ "                \"State\": \"UP\",\r\n"
				+ "                \"Postal\": \"201016\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"InquiryPhones\": [\r\n"
				+ "            {\r\n"
				+ "                \"seq\": \"1\",\r\n"
				+ "                \"Number\": \"9431046500\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"IDDetails\": [\r\n"
				+ "            {\r\n"
				+ "                \"seq\": \"1\",\r\n"
				+ "                \"IDType\": \"T\",\r\n"
				+ "                \"IDValue\": \"CJRPK4585N\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"DOB\": \"1993-11-12\",\r\n"
				+ "        \"Gender\": \"M\",\r\n"
				+ "        \"CustomFields\": [\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"DEDUPE_FLAG\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"EDUCATION\",\r\n"
				+ "                \"value\": \"Diploma\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NO_TIMES_SUSPENDED\",\r\n"
				+ "                \"value\": \"1\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_SMSES_CAT\",\r\n"
				+ "                \"value\": \"919\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NO_CALLS_KNWLTY_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SECS_25_50\",\r\n"
				+ "                \"value\": \"20961\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"ES_CLICKS\",\r\n"
				+ "                \"value\": \"13\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"APP_CLICKS_CAT\",\r\n"
				+ "                \"value\": \"13\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SAL_45_DAY\",\r\n"
				+ "                \"value\": \"Y\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SALARY_NOT_IDENTIFIED\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NUM_BOUNCES_PERF\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"BOUNCES\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"DECLARATION_BUCKET\",\r\n"
				+ "                \"value\": \"B_High\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"IMPS_FLAG\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"ALCOHOL_PERF_CAT\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"CREDIT_CARD_PAYMENT_PERF_CAT\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"INSURANCE_PERF_CAT\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NUM_CASH_DEPOSITS_PERF\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"PERFIOS_BOUNCES3M_TOTAL_BOUNCES_CAT\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"AVERAGE_DAILY_BALANCE_CAT\",\r\n"
				+ "                \"value\": \"2362\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"LATEST_BAL_BINNED\",\r\n"
				+ "                \"value\": \"26221.18\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TRANSFER_FROM_500_10K_BINNED\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TRANSFER_OUT_500_5K_BINNED\",\r\n"
				+ "                \"value\": \"5\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"INVESTMENT_SUM_BINNED\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_NO_OF_CASH_W_D_2_MONTHS_BINNED\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"UTILITY_APP_COUNT_BINNED\",\r\n"
				+ "                \"value\": \"8\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"WALLET_APP_COUNT_BINNED\",\r\n"
				+ "                \"value\": \"2\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NEWS_INFORMATION_OUTLETS_APP_COUNT_BINNED\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"COMPETITOR_APP_COUNT_BINNED\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"HEALTH_APP_COUNT_BINNED\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"RESIDENCE_TYPE\",\r\n"
				+ "                \"value\": \"on rent\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SALARY\",\r\n"
				+ "                \"value\": \"21272.5\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"FB_FRIEND_DEFAULT\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"USER_ID\",\r\n"
				+ "                \"value\": \"176\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"REPORT_ORDER_NUMBER\",\r\n"
				+ "                \"value\": \"537406\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"FB_CONNECTIONS_CAT\",\r\n"
				+ "                \"value\": \"1332\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"NUM_APPROVALS_OFF_PINCODE_CAT\",\r\n"
				+ "                \"value\": \"846\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_INCOMING_DURATION_SECS_CAT\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SOURCE_TYPE\",\r\n"
				+ "                \"value\": \"ANDROID\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"DPD_30\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"INCOMING_OVERALL_CALL_RATIO\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"AVGCALLSPERDAY_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_UNIQUE_CATEGORIES_CAT\",\r\n"
				+ "                \"value\": \"14\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"CASINO_GAMING_APPS_CAT\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TRAVEL_APPS_CAT\",\r\n"
				+ "                \"value\": \"4\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"AGE\",\r\n"
				+ "                \"value\": \"24\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"INCOMING_DURATION_HRS_CALL_HIST_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"CORP_FLAG\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"JOURNEY_REJECT_FRNDS_PHBK_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"OVERDUE_SMSES_COUNT\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"FB_CONN_CAT\",\r\n"
				+ "                \"value\": \"1332\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"COMP_LOAN_FLAG\",\r\n"
				+ "                \"value\": \"N\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"CHANNEL\",\r\n"
				+ "                \"value\": \"APP\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"WORKFLOW_ID\",\r\n"
				+ "                \"value\": \"3\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"SMALL_CITY\",\r\n"
				+ "                \"value\": \"0\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_DURATION_SECS_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"TOTAL_CONTACTS_PHBK_CAT\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"EXPERIENCE_MONTHS_CAT\",\r\n"
				+ "                \"value\": \"37\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"key\": \"FILE_TYPE\",\r\n"
				+ "                \"value\": \"ntc\"\r\n"
				+ "            }\r\n"
				+ "        ]\r\n"
				+ "    }\r\n"
				+ "}";
		
		given()
			.contentType("application/json")
			.body(APP_NTC_PayLoad)
		.when()
			.post()
		.then()
			.statusCode(200)
			.body("InquiryRequestInfo.InquiryPurpose", equalTo("05"))
			.body("InquiryResponseHeader.SuccessCode", is("0"));
	}

	
	
}
